myfirst/apps/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment')
]

myfirst/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('Nova_article/', include("articles.urls")),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
]

myfirst/apps/articles/models.py
from django.db import models
import datetime
from django.utils import timezone


# Create your models here.

class Article(models.Model):
    article_title = models.CharField('Name_of_article', max_length=30)
    article_text = models.TextField('Text_of_article')
    publishing_date = models.DateTimeField('Date_of_publishing')

    def __str__(self):
        return self.article_title

    def was_published_in_two_days(self):
        return self.publishing_date >= (timezone.now() - datetime.timedelta(days=7))


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('Name_of_author', max_length=30)
    comment_text = models.CharField('Comment_text', max_length=500)

    def __str__(self):
        return self.author_name

myfirst/apps/articles/views.py
from django.shortcuts import render
from .models import Article, Comment
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse


def index(request):
    latest_articles_list = Article.objects.order_by('-publishing_date')[:10]
    return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list})


def detail(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Artile not found :(")

    latest_comments_list = a.comment_set.order_by('-article_id')[:5]
    return render(request, 'articles/detail.html', {'article': a, 'latest_comments_list': latest_comments_list})


def leave_comment(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Artile not found :(")

    Comment.objects.create(
        article=a,
        author_name=request.POST.get('name'),
        comment_text=request.POST.get('text')
    )
    return HttpResponseRedirect(reverse('articles:detail', args=(a.id,)))

myfirst/templates/articles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Nova_Strike_site{% endblock %}</title>
    <link rel="stylesheet" href="static 'css'" type="text/css">
</head>
<body>
{% block content %} {% endblock %}
</body>
</html>

myfirst/templates/articles/detail.html
{% extends 'articles/base.html' %}
{% block title %} {{ article.article_title }}{% endblock %}
{% block content %}
    <h2>{{ article.article_title }}</h2>
    <p>{{ article.article_text }}</p>
    <em>{{ article.publishing_date }}</em>
    <hr>
    {% if latest_comments_list %}
        {% for foo in latest_comments_list.all %}
            <p><strong>{{ foo.author_name }}</strong></p>
            <p>{{ foo.comment_text }}</p>
        {% endfor %}

    {% else %}
        Coments not found
    {% endif %}

    <hr>
    <form action="{% url 'articles:leave_comment' article.id %}" method="POST">
        {% csrf_token %}
        <label>
            <input type="text" required placeholder="Your name" name="name">
        </label><br>
        <label>
            <textarea name="text" required="" placeholder="Comment text:" cols="30" rows="10"></textarea>
        </label><br>
        <button type="submit">Post comment</button>
    </form>
{% endblock %}

myfirst/templates/articles/list.html
{% extends 'articles/base.html' %}
{% block title %} last articles{% endblock %}
{% block content %}
    {% if latest_articles_list %}
        {% for a in latest_articles_list %}
            <li><a href="{% url 'articles:detail' a.id %}">
                {{ a.article_title }}</a></li>
        {% endfor %}
    {% else %}

    {% endif %}
{% endblock %}